version: '3.8'

services:
  app:
    image: dhafersouid/devopsproject:1.0.0 # Replace this with the actual image name and tag DevOps_Project-1.0
    container_name: devopsfinal_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/devopsfinal?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword # Update with a secure password if needed
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: devopsfinal_db
    environment:

      MYSQL_DATABASE: devopsfinal
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql



volumes:
  db_data:
